---
title: "Data cleaning"
output: pdf_document
date: "2024-04-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load in datasets
```{r}
library("readxl")
views_global <- read_excel("../all-weeks-global.xlsx")
head(views_global)
sum(grepl("Film", views_global$category))
sum(grepl("TV", views_global$category))
views_us <- read.csv("../all-weeks-us.csv")
head(views_us)
netflix <- read.csv("../netflix.csv")
head(netflix)
```
## filter out genres
```{r}
library(dplyr)
netflix_filtered <- select(netflix, c("title", "date_added", "listed_in"))
head(netflix_filtered)
genres <- unique(unlist(strsplit(netflix_filtered$listed_in, ", ")))
genre_counts <- data.frame(genre=character(), true_count=integer(), false_count=integer())
genres
for (genre in genres) {
  genre_col <- sapply(netflix_filtered$listed_in, function(x) genre %in% strsplit(x, ", ")[[1]])
  netflix_filtered[paste("genre", genre, sep = "_")] <- genre_col
  true_count <- sum(genre_col)
  false_count <- nrow(netflix_filtered) - true_count
  genre_counts <- rbind(genre_counts, data.frame(genre=genre, true_count=true_count, false_count=false_count))
}
genre_counts_filtered <- subset(genre_counts, true_count > 1000)
netflix_filtered_by_genre <- select(netflix_filtered, c("title", "date_added", "genre_International TV Shows", "genre_Dramas", "genre_Comedies", "genre_International Movies"))
netflix_filtered_by_genre$genre_International <- netflix_filtered_by_genre$`genre_International Movies` | netflix_filtered_by_genre$`genre_International TV Shows`
sum(netflix_filtered_by_genre$genre_International)/nrow(netflix_filtered_by_genre)
```


## add in awards in global views dataframe
```{r}
views_global$awards <- FALSE
award_titles <- c("BEEF", "Big Mouth", "DAHMER", 
                  "Entergalactic", "Guillermo del Toro's Cabinet of Curiosities", "I Think You Should Leave With Tom Robinson", "John Mulaney: Baby J", "Queen Charlotte: A Bridgerton Story", "Queer Eye", "Wednesday", "Working: What We Do All Day", "Arcane", "Love, Death + Robots", "The House", "Arcane", "Bridgerton", "Love on the Spectrum U.S.", "Our Great National Parks", "Ozark", "Squid Game", "Stranger Things", "Bo Burnham: Inside", "Country Comfort", "David Attenborough: A Life on Our Planet", "Dick Johnson is Dead", "Dolly Parton's Christmas On the Square", "Halston", "The Crown", "The Queen's Gambit", "The Social Dilemma", "The Wonderful Story of Henry Sugar", "All Quiet on the Western Front", "Guillermo del Toro's Pinocchio", "The Elephant Whisperers", "The Power of the Dog", "If Anything Happens I Love You", "Ma Rainey's Black Bottom", "Mank", "My Octopus Teacher", "Two Distant Strangers", "The Harder They Fall", "His House", "Jimmy Savile: A British Horror Story", "The Tinder Swindler", "Top Boy", "The Witcher", "Fear City: New York vs The Mafia", "Sex Education: Season 2", "The Surgeon's Cut")
views_global$awards[views_global$show_title %in% award_titles | views_global$season_title %in% award_titles] <- TRUE
views_global
```

## join onto views_global
```{r}
library(tidyr)
df_global <- left_join(views_global, netflix_filtered_by_genre, by =c('show_title'='title'))
sum(is.na(df_global$genre_Comedies))/5880
df_global_genres <- drop_na(df_global, genre_International) 
df_global_genres <- select(df_global_genres, -c("episode_launch_details", "date_added"))
# extract language
df_global_genres$english <- TRUE
df_global_genres$english[grepl("Non-English", df_global_genres$category)] <- FALSE
# extract film/TV. true: TV false: film
df_global_genres$tv <- TRUE
df_global_genres$tv[grepl("Film", df_global_genres$category)] <- FALSE
```

## separate into film dataset and tv dataset, perform mice for runtime
```{r}
df_global_genres_tv <- subset(df_global_genres, tv==TRUE)
df_global_genres_tv <- select(df_global_genres_tv, -c("genre_International TV Shows", "genre_International Movies", "category", "tv"))
df_global_genres_film <- subset(df_global_genres, tv==FALSE)
df_global_genres_film <- select(df_global_genres_film, -c("genre_International TV Shows", "genre_International Movies", "category", "tv"))
# mice on tv
library(mice)
summary(df_global_genres_tv)
md.pattern(df_global_genres_tv)
#slightly right-skewed, enough observed data for MICE
ggplot(df_global_genres_tv, aes(x=runtime)) + 
  geom_histogram(binwidth = 0.8, fill = "skyblue", color = "black") +
  theme_minimal() +
  labs(title = "Distribution of Runtime of Weekly Top 10 Netflix TV Shows")

predictorMatrix <- matrix(0, nrow = 6, ncol = 6, dimnames = list(c("runtime", "weekly_hours_viewed", "is_staggered_launch", "genre_International", "genre_Dramas", "genre_Comedies"), c("runtime", "weekly_hours_viewed", "is_staggered_launch", "genre_International", "genre_Dramas", "genre_Comedies")))

# Set up predictors for runtime
predictorMatrix["runtime", "weekly_hours_viewed"] <- 1
predictorMatrix["runtime", "is_staggered_launch"] <- 1
predictorMatrix["runtime", "genre_International"] <- 1
predictorMatrix["runtime", "genre_Dramas"] <- 1
predictorMatrix["runtime", "genre_Comedies"] <- 1

#adjust pred matrix to match main analysis model
df_global_genres_tv$season <- as.integer(sub(".*(?:Season|Part) (\\d+).*", "\\1", df_global_genres_tv$season_title))
df_global_genres_tv <- df_global_genres_tv %>%
  mutate(season = if_else(is.na(season), 1, season))

df_global_genres_tv$weekly_views_logged <- log(df_global_genres_tv$weekly_hours_viewed)
predMatrix2 <- matrix(0, nrow = 7, ncol = 7, dimnames = list(c("runtime", "weekly_views_logged","genre_Comedies", "genre_Drama", "season", "english", "awards"), c("runtime", "weekly_views_logged","genre_Comedies", "genre_Drama", "season", "english", "awards")))
predMatrix2["runtime", "genre_Comedies"] <- 1
predMatrix2["runtime", "genre_Drama"] <- 1
predMatrix2["runtime", "season"] <- 1
predMatrix2["runtime", "english"] <- 1
predMatrix2["runtime", "awards"] <- 1
predMatrix2["runtime", "weekly_views_logged"] <- 1

imputed_data <- mice(df_global_genres_tv, method = "pmm", m=6, seed=123, predictorMatrix = predictorMatrix)
completed_tv <- complete(imputed_data, 4)
sum(completed_tv$runtime==0)
summary(completed_tv$runtime)
```

```{r}
#convert genre to factor
df_global_genres_film$genre <- apply(df_global_genres_film[, c("genre_International", "genre_Dramas", "genre_Comedies")], 1, function(x) {
  if(x["genre_International"]) {
    return("International")
  } else if(x["genre_Dramas"]) {
    return("Drama")
  } else if(x["genre_Comedies"]) {
    return("Comedy")
  } else {
    return("Other")  # for rows where none of the genres are TRUE or applicable
  }
})

# Convert the 'genre' column to a factor
df_global_genres_film$genre <- as.factor(df_global_genres_film$genre)

predMatrix <- matrix(0, nrow = 4, ncol = 4, dimnames = list(c("runtime", "weekly_hours_viewed", "is_staggered_launch", "genre"), c("runtime", "weekly_hours_viewed", "is_staggered_launch", "genre")))
predMatrix["runtime", "weekly_hours_viewed"] <- 1
predMatrix["runtime", "genre"] <- 1
predMatrix["runtime", "is_staggered_launch"] <- 1

imputed_film <- mice(df_global_genres_film, method = "pmm", m=6, seed=250, predMatrix = predictorMatrix)
completed_film <- complete(imputed_film, 1)
sum(completed_film$runtime==0)
summary(completed_film$runtime)
```
## use random sample imputation to preserve distribution for film runtime
```{r}
library(ggplot2)
summary(df_global_genres_film)
#normally distributed, close mean and median, not enough observed data
ggplot(df_global_genres_film, aes(x=runtime)) + 
  geom_histogram(binwidth = 0.2, fill = "skyblue", color = "black") +
  theme_minimal() +
  labs(title = "Distribution of Runtime of Weekly Top 10 Netflix Films")

# Random sample imputation
set.seed(123)  # for reproducibility
df_global_genres_film$runtime[is.na(df_global_genres_film$runtime)] <- sample(df_global_genres_film$runtime[!is.na(df_global_genres_film$runtime)], sum(is.na(df_global_genres_film$runtime)), replace = TRUE)
summary(df_global_genres_film$runtime)
```

## calculate weekly_views
```{r}
#drop rows with zero runtime

df_global_genres_tv_filtered <- completed_tv[completed_tv$runtime>0.0000,]
sum(df_global_genres_tv_filtered$runtime==0)
nrow(df_global_genres_tv_filtered)

completed_tv_views <- df_global_genres_tv_filtered %>%
  mutate(weekly_views = if_else(is.na(weekly_views), weekly_hours_viewed / runtime, weekly_views))

#add in season
completed_tv_views$season <- as.integer(sub(".*(?:Season|Part) (\\d+).*", "\\1", completed_tv_views$season_title))
completed_tv_views <- completed_tv_views %>%
  mutate(season = if_else(is.na(season), 1, season))
  
#add in limited series
completed_tv_views$is_limited_series <- FALSE
completed_tv_views$is_limited_series[grepl("Limited Series", completed_tv_views$season_title)] <- TRUE

df_film <- df_global_genres_film[df_global_genres_film$runtime>0.0000,]
nrow(df_film)

completed_film_views <- df_film %>%
  mutate(weekly_views = if_else(is.na(weekly_views), weekly_hours_viewed / runtime, weekly_views)) 

completed_film_views <- select(completed_film_views, -c(season_title))
```

## export
```{r}
write.csv(completed_tv_views, "global_tv.csv")
write.csv(completed_film_views, "global_film.csv")
```


